### ISSUE TITLE
user disconnects after 1s (chrome 40)

### ISSUE THREAD

**Issue by 6Beaufort** [mgechev/ReactChat#1]
Just tested between Chrome 40 and Firefox 36 on Mac 10.9.5.

The user registered with chrome is visible for 1s and then disappears from the userlist in firefox. server shows that the chrome user disconnects automatically and does not reconnect. probably not the intended behavior.

Safari shows no error but doesn't work of course (no WebRTC support). Would be better to check if WebRTC is available or not.

**Comment by mgechev** [comment]
There was a bug in PeerJS version 0.3.9.

After update to 0.3.14, everything works properly. I updated `bower.json` so everything should be alright now.

---

About notifying the user in case her browser doesn't support WebRTC, we can open different issue.
