### ISSUE TITLE
Not sure how to run

### ISSUE THREAD

**Issue by asael2** [mgechev/ReactChat#3]
Cant run it, installing grunt, npm install, or similar, can you tellme how are you starting your app please. Thanks!

-Asael

**Comment by mgechev** [comment]
Take a look at the [readme](https://github.com/mgechev/ReactChat#instructions).

**Comment by asael2** [comment]
Hi! Im not sure why but this is what I receive:
$ npm install
$ npm WARN package.json react-peerjs@0.0.0 No repository field.

**Comment by mgechev** [comment]
This is not an error, only a warning. Follow the readme and you shouldn't have any issues.
